#if !canImport(ObjectiveC)
import XCTest

extension Alice_swiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Alice_swiftTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Alice_swiftTests.__allTests__Alice_swiftTests),
    ]
}
#endif
